#####################################################################
# Description: Reading and consolidating all the files generated by
#              SAS model into the required Kaggle submission format
# 
# Kaggle contest description, rules and data: 
# http://www.kaggle.com/c/walmart-recruiting-store-sales-forecasting
# 
# Author: Vignan Uppugandla <vignan.uppugandla@sv.cmu.edu> 
#####################################################################

#set the working directory to read the files
setwd('F:/DataFiles/SAS_Output')

#gathering the required packages
require(dplyr)
require(gtools)

#importing the sampleSubmssion file provided by Walmart
sampleSubmission<- read.csv(file='F:/DataFiles/Old/sampleSubmission.csv',header=T)

#reading all the files with name "store*" format
files <- list.files(pattern = "store")
files<-mixedsort(files) #sorting the alphanumeric file names


#looping through each file
for(i in seq_along(files)){
 assign(paste('store',i,sep=''),read.csv(files[i],header=T))
}

#removing the temp files/variables that are not required
rm(files,i,test,stores,store,final)

#creating a list with the stores names
stores<-list(store1,store2,store3,store4,store5,store6,store7,store8,store9,store10,store11,store12,store13,store14,store15
            ,store16,store17,store18,store19,store20,store21,store22,store23,store24,store25,store26
            ,store27,store28,store29,store30,store31,store32,store33,store34,store35,store36,store37
            ,store38,store39,store40,store41,store42,store43,store44,store45)

#store num that will be incremented in the loop
storenum=0
#iterating through data for each store
for(store in stores){
 storenum=storenum+1
 
 #converting the date into character
 store$DATE<-as.Date(store$DATE,format="%m/%d/%y")
 store$DATE<-as.character(store$DATE)
 
 #selecting only the required columns into a temporary data frame
 storeA<-store
 storeA<-select(storeA,DEPT1_SALES:DEPT99_SALES)

 dept=0
 #iterating through the departments in the store
 for(i in names(storeA)){
  dept<-dept+1
  if(i=='DEPT1_SALES'&&storenum==1){
   Store1<-data.frame(Id=paste(storenum,dept,store$DATE,sep='_')
                      ,Weekly_Sales=storeA[,eval(i)])
  }else if(dept==15|dept==53|dept==57|dept==61|dept==62|dept==63|dept==64|dept==66|dept==68|dept== 69|dept==70|dept==73|dept==75|dept==76|dept==84|dept==86|dept==88|dept==89){
   next   
  }else{
   Store1<-rbind(Store1,data.frame(Id=paste(storenum,dept,store$DATE,sep='_')
                                   ,Weekly_Sales=storeA[,eval(i)]))
  }
 }
 print(storenum)#checking the progress with the store num
}

#checking the ID values in sampleSubmission from Walmart
sS.Id<-sort(unique(sampleSubmission$Id))
head(sort(unique(Store1$Id)))

#removing the data that is not available in sampleSubmission
arima<-Store1[Store1$Id %in% sS.Id,]

#writing the data on to .csv file for submission to walmart
write.csv(arima,file="Arima_Forecast_Auto_removed.csv")